name = "apimap"
compatibility_date = "2024-12-31"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"


[vars]
DEEPSEEK_API_URL = "https://api.deepseek.com"
ALLOWED_ORIGINS = "http://localhost:3000,https://yourdomain.com"
NODE_ENV = "production"
TURSO_DB_URL = "libsql://apimap.turso.io"
FIREBASE_AUTH_DOMAIN = "amap-ed2dd.firebaseapp.com"
FIREBASE_STORAGE_BUCKET = "amap-ed2dd.appspot.com"
FIREBASE_API_KEY = "AIzaSyC4uUXtnYqPvlOmFvh0Uv22PETxyDnMXjA"

# [ai]
# binding = "AI"

[dev]
port = 8787

[[r2_buckets]]
binding = "R2"
bucket_name = "apimap"
preview_bucket_name = "apimap-dev"  # 開発環境用
